In [22]:
import pandas as pd
import numpy as np
import json
import os
import datetime

In [3]:
os.getcwd()

'/Users/yiwen/Desktop/Fetch Rewards'

#### Receipts table

In [58]:
def date_transfer(milliseconds):
    if milliseconds is None:
        return None
    return datetime.datetime.fromtimestamp(milliseconds/1000.0).strftime("%Y-%m-%d")

In [80]:
receipts = []
with open('data/receipts.json') as f:
    for line in f:
        receipts.append(json.loads(line))

rcp_id_list = []
bonusPointsEarned_list = []
createDate_list = []
dateScanned_list = []
finishedDate_list = []
modifyDate_list = []
pointsAwardedDate_list = []
pointsEarned_list = []
purchaseDate_list = []
purchasedItemCount_list = []
barcode_list = []
description_list = []
finalPrice_list = []
itemPrice_list = []
quantityPurchased_list = []
rewardsReceiptStatus_list = []
totalSpent_list = []
userId_list = []

for i in range(len(receipts)):
    rcp = receipts[i]
    if rcp.get('rewardsReceiptItemList', None):
        for j in range(len(rcp['rewardsReceiptItemList'])):
            rcp_id = rcp['_id']['$oid']
            bonusPointsEarned = rcp.get('bonusPointsEarned', None)
            createDate = date_transfer(rcp.get('createDate').get('$date', None))
            dateScanned = date_transfer(rcp.get('dateScanned').get('$date', None))
            finishedDate = date_transfer(rcp.get('finishedDate', None).get('$date', None) if rcp.get('finishedDate', None) else None)
            modifyDate = date_transfer(rcp.get('modifyDate').get('$date', None))
            pointsAwardedDate = date_transfer(rcp.get('pointsAwardedDate').get('$date', None) if rcp.get('pointsAwardedDate', None) else None)
            pointsEarned = rcp.get('pointsEarned', None)
            purchaseDate = date_transfer(rcp.get('purchaseDate').get('$date', None) if rcp.get('purchaseDate', None) else None)
            purchasedItemCount = rcp.get('purchasedItemCount', None)
            barcode = rcp['rewardsReceiptItemList'][j].get('barcode', None)
            description = rcp['rewardsReceiptItemList'][j].get('description', None)
            finalPrice = rcp['rewardsReceiptItemList'][j].get('finalPrice', None)
            itemPrice = rcp['rewardsReceiptItemList'][j].get('itemPrice', None)
            quantityPurchased = rcp['rewardsReceiptItemList'][j].get('quantityPurchased', None)
            rewardsReceiptStatus = rcp.get('rewardsReceiptStatus', None)
            totalSpent = rcp.get('totalSpent', None)
            userId = rcp.get('userId', None)
            rcp_id_list.append(rcp_id)
            bonusPointsEarned_list.append(bonusPointsEarned)
            createDate_list.append(createDate)
            dateScanned_list.append(dateScanned)
            finishedDate_list.append(finishedDate)
            modifyDate_list.append(modifyDate)
            pointsAwardedDate_list.append(pointsAwardedDate)
            pointsEarned_list.append(pointsEarned)
            purchaseDate_list.append(purchaseDate)
            purchasedItemCount_list.append(purchasedItemCount)
            barcode_list.append(barcode)
            description_list.append(description)
            finalPrice_list.append(finalPrice)
            itemPrice_list.append(itemPrice)
            quantityPurchased_list.append(quantityPurchased)
            rewardsReceiptStatus_list.append(rewardsReceiptStatus)
            totalSpent_list.append(totalSpent)
            userId_list.append(userId) 

    else:
        rcp_id = rcp['_id']['$oid']
        bonusPointsEarned = rcp.get('bonusPointsEarned', None)
        createDate = date_transfer(rcp.get('createDate').get('$date', None))
        dateScanned = date_transfer(rcp.get('dateScanned').get('$date', None))
        finishedDate = date_transfer(rcp.get('finishedDate', None).get('$date', None) if rcp.get('finishedDate', None) else None)
        modifyDate = date_transfer(rcp.get('modifyDate').get('$date', None))
        pointsAwardedDate = date_transfer(rcp.get('pointsAwardedDate').get('$date', None) if rcp.get('pointsAwardedDate', None) else None)
        pointsEarned = rcp.get('pointsEarned', None)
        purchaseDate = date_transfer(rcp.get('purchaseDate').get('$date', None) if rcp.get('purchaseDate', None) else None)
        purchasedItemCount = rcp.get('purchasedItemCount', None)
        barcode = None
        description = None
        finalPrice = None
        itemPrice = None
        quantityPurchased = None
        rewardsReceiptStatus = rcp.get('rewardsReceiptStatus', None)
        totalSpent = rcp.get('totalSpent', None)
        userId = rcp.get('userId', None)        

        rcp_id_list.append(rcp_id)
        bonusPointsEarned_list.append(bonusPointsEarned)
        createDate_list.append(createDate)
        dateScanned_list.append(dateScanned)
        finishedDate_list.append(finishedDate)
        modifyDate_list.append(modifyDate)
        pointsAwardedDate_list.append(pointsAwardedDate)
        pointsEarned_list.append(pointsEarned)
        purchaseDate_list.append(purchaseDate)
        purchasedItemCount_list.append(purchasedItemCount)
        barcode_list.append(barcode)
        description_list.append(description)
        finalPrice_list.append(finalPrice)
        itemPrice_list.append(itemPrice)
        quantityPurchased_list.append(quantityPurchased)
        rewardsReceiptStatus_list.append(rewardsReceiptStatus)
        totalSpent_list.append(totalSpent)
        userId_list.append(userId)   
        
receipts_df = pd.DataFrame({'rcp_id': rcp_id_list})

column_nm ={'bonusPointsEarned':bonusPointsEarned_list, 'createDate':createDate_list, 
            'dateScanned':dateScanned_list, 'finishedDate':finishedDate_list,
            'modifyDate':modifyDate_list, 'pointsAwardedDate':pointsAwardedDate_list, 
            'pointsEarned':pointsEarned_list, 'purchaseDate':purchaseDate_list, 
            'purchasedItemCount':purchasedItemCount_list, 'barcode':barcode_list, 
            'description':description_list, 'finalPrice':finalPrice_list, 'itemPrice':itemPrice_list,
            'quantityPurchased':quantityPurchased_list, 'rewardsReceiptStatus':rewardsReceiptStatus_list, 
            'totalSpent':totalSpent_list, 'userId':userId_list}


for col_nm, col in column_nm.items():
    receipts_df[col_nm] = col

In [81]:
receipts_df

,rcp_id,bonusPointsEarned,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,barcode,description,finalPrice,itemPrice,quantityPurchased,rewardsReceiptStatus,totalSpent,userId
0,5ff1e1eb0a720f0523000575,500.0,2021-01-03,2021-01-03,2021-01-03,2021-01-03,2021-01-03,500.0,2021-01-02,5.0,4011,ITEM NOT FOUND,26.00,26.00,5.0,FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,2021-01-03,2021-01-03,2021-01-03,2021-01-03,2021-01-03,150.0,2021-01-02,2.0,4011,ITEM NOT FOUND,1,1,1.0,FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,5ff1e1bb0a720f052300056b,150.0,2021-01-03,2021-01-03,2021-01-03,2021-01-03,2021-01-03,150.0,2021-01-02,2.0,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,1.0,FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
3,5ff1e1f10a720f052300057a,5.0,2021-01-03,2021-01-03,None,2021-01-03,None,5,2021-01-02,1.0,None,None,None,None,NaN,REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
4,5ff1e1ee0a7214ada100056f,5.0,2021-01-03,2021-01-03,2021-01-03,2021-01-03,2021-01-03,5.0,2021-01-02,4.0,4011,ITEM NOT FOUND,28.00,28.00,4.0,FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,603d0b710a720fde1000042a,NaN,2021-03-01,2021-03-01,None,2021-03-01,None,None,None,NaN,None,None,None,None,NaN,SUBMITTED,None,5fc961c3b8cfca11a077dd33
7377,603cf5290a720fde10000413,NaN,2021-03-01,2021-03-01,None,2021-03-01,None,None,None,NaN,None,None,None,None,NaN,SUBMITTED,None,5fc961c3b8cfca11a077dd33
7378,603ce7100a7217c72c000405,25.0,2021-03-01,2021-03-01,None,2021-03-01,None,25.0,2020-08-16,2.0,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,1.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7379,603ce7100a7217c72c000405,25.0,2021-03-01,2021-03-01,None,2021-03-01,None,25.0,2020-08-16,2.0,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,1.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7380,603c4fea0a7217c72c000389,NaN,2021-02-28,2021-02-28,None,2021-02-28,None,None,None,NaN,None,None,None,None,NaN,SUBMITTED,None,5fc961c3b8cfca11a077dd33

In [82]:
receipts_df['rewardsReceiptStatus']

0        FINISHED
1        FINISHED
2        FINISHED
3        REJECTED
4        FINISHED
          ...
7376    SUBMITTED
7377    SUBMITTED
7378     REJECTED
7379     REJECTED
7380    SUBMITTED
Name: rewardsReceiptStatus, Length: 7381, dtype: object

In [108]:
receipts_df['barcode'].unique()

array(['4011', '028400642255', None, '1234', '046000832517',
       '013562300631', '034100573065', '075925306254', '041000168468',
       '2700719497082', '079400066619', '051500720011', '087684001127',
       '071040063102', '029000079236', '041129002292', '043000946060',
       '044700009888', '021000012961', '021000678358', '044700033302',
       '021000059232', '043000004944', '759283400082', '025800000135',
       '043000043486', '029000024748', '044700002810', '043000079904',
       '044000000745', '046704085905', '021000057832', '021000002917',
       '044700019917', '043000035818', '070085046583', '044700073377',
       '021000055920', '021000051885', '022174070214', '043000012871',
       '043000077467', '043000008836', '021000068364', '021000013869',
       '044700030479', '041258081601', '043000075821', '021000667543',
       '013120013966', '021000068760', '070277290107', '041129088005',
       '013000993906', '043000065198', '021000050765', '021000032778',
       '043000046814', '686924560242', '021000051113', '021000070787',
       '043000058145', '044700074602', '021000007561', '043000013229',
       '043000000960', '013000657600', '017696004519', '012000809941',
       '028400642033', '036000391718', '044700092408', '043000023440',
       '029000016187', '021000001361', '029000020344', '043000009604',
       '021000024834', '071159020195', '043000204399', '021908236865',
       '043000060544', '021000034574', '043000057162', '044700096284',
       '686924155783', '016000156234', '305210154278', '001111132666',
       '089203700016', '079400245328', '001111147332', '079400236425',
       '016000493025', '043000066706', '043000000175', '043000082294',
       '043000955628', '072785048119', '043000206515', '043000061978',
       '044700071533', '025800026302', '021000007660', '070085035006',
       '686924820858', '798813118547', '077567000637', '021000068159',
       '021000648863', '029000023666', '043000078488', '043000071182',
       '043000062760', '021000725403', '021000024858', '044700076422',
       '051600001003', '076840100354', '311111511867', '041000022623',
       '076840580750', '028435383253', '070470137735', '011111326231',
       '043000000199', '822142991523', '043000043790', '036632011077',
       '075706191031', '019600920106', '028189000079', '754500326305',
       '058496723002', '058449450023', '075450093070', '048500256763',
       '4816', '4166', '075450120400', '754500797204', '075450085150',
       '071007023095', '072310001459', '754502285808', '041390024368',
       '511111204206', '043000716021', '044500341720', '754500958803',
       '024105590051', '21251000000', '4060', '048500052020', '4069',
       '4093', '754500973400', '075450079760', '754500947807',
       '039400015031', '025500204215', '754501311409', '754500355602',
       '018627030010', '041000004087', '021000604647', '071146002487',
       '754501734109', '071430010051', '754500638101', '511111001485',
       '305731769135', '048000007070', '015300430594', '009800300037',
       '754500990209', '014113911979', '028800296737', '071100007299',
       '036632037541', '036632013095', '084114111722', '511111104537',
       '014113910026', '815473013279', '028400643061', '689544081937',
       '037000979715', '085718300512', '078742112138', '633472322587',
       '029000019034', '052100587967', '078742348315', '042222302005',
       '681131122764', '857484001159', '689544083405', '887214041018',
       '045255148947', '681131091206', '026542084018', '068113135477',
       '041235000687', '037466017631', '076828048432', '021000040247',
       '021000612239', '078000082401', '013120014178', '075706304783',
       '036000485967', '000980000069', '078742052328', '041483022226',
       '078742333960', '015800030621', '007874242956', '078742372198',
       '754500947500', '754501315209', '041500220208', '754500024805',
       '754500486009', '038000924224', '611443010787', '046000721835',
       '014100095071', '043000285213', '030100001331', '041289895406',
       '021000024926', '4759', '3332', '4608', '016000363779',
       '311111242129', '754500363409', '884912006806', '605806001307',
       '011110916600', '082242012362', '046000400280', '073410955505',
       '046000288697', '511111502142', '4225', '075856000269',
       '26623200000', '305731769203', '22', '043000041994',
       '043000068649', '021000051038', '043000063897', '029000016705',
       '044700096321', '044700070840', '070085038403', '044700065617',
       '043000971635', '686924113172', '043000075340', '021000054862',
       '021000679201', '087684002872', '071871542067', '025800000524',
       '013000010917', '013000000635', '029000021273', '071040063188',
       '021000054961', '021000007363', '019582000117', '021000604906',
       '021000644551', '043000204443', '021000029778', '044700072813',
       '044700087145', '044700087329', '016000151024', '077567304124',
       '044700064238', '013120000843', '021000006106', '511111802358',
       '012000809965', '511111101451', '005111116022', '511111602118',
       '311111536044', '074682200294', '011594404013', '013000006187',
       '021000065547', '311111806949', '012000810022', '815473010360',
       '013000798952', '044700071748', '043000032275', '044700024119',
       '028400081382', '021000046904', '053000069867', '012000004919',
       '815473012357', '036000119749', '048001154032', '041000022906',
       '016300165912', '028400641326', '028400003988', '029000074361',
       '043000061732', '021000068036', '686924291290', '025800000159',
       '021000633609', '030000562383', '737628011506', '021000615315',
       '015000056087', '4068', '021000039340', '94094', '896859000489',
       '036000478044', '016000496361', '013800190215', '048001213517',
       '025500202310', '311111452382', '021834033316', '23572500000',
       '012000106057', '012000000171', '012000010736', '043000050910',
       '071100211474', '4540', '4090', '612669316714', '041129411506',
       '311111603920', '044000043254', '048001154049', '071100006681',
       '021000065127', '044700098752', '4061', '311111705006',
       '044700061909', '511111901587', '021000026999', '4066',
       '021000701445', '4562', '016000877009', '052100625348',
       '025500005188', '029000017986', '023400022212', '041695151721',
       '071100200058', '072310001244', '044000034030', '044000051051',
       '072220001808', '016000854307', '311111434807', '016000126855',
       '020709100139', '021000037490', '022000014252', '029000073692',
       '511111902690', '311111149350', '071100309744', '311111445421',
       '041800200139', '070158008678', '511111704140', '861745000010',
       '4662', '511111104186', '041235000328', '4614', '013120002588',
       '070492140003', '051700788262', '041483030917', '311111208538',
       '020169222341', '074904100104', '011110876942', '011110857132',
       '052100037509', '029000016156', '044600020020', '041321006357',
       '041695951130', '037466016023', '016000123151', '4023', '3435',
       '011110973009', '011110847454', '034695123621', '051611165893',
       '071279275024', '076840400218', '071430000724', '016000124790',
       '3283', '511111518044', '94023', '4072', '013800100320', '4563',
       '070446400009', '029000021723', '041196277470', '076001350437',
       '4053', '013800104083', '071100007077', '074714086827',
       '021000744152', '085000015889', '046704096802', '043000956113',
       '044700075302', '077661120460', '034000056644', '011110916068',
       '021000069293', '021000068883', '025155000149', '043000062753',
       '759283001890', '043000000342', '016000437760', '021000045129',
       '038000052200', '038000138577', '041695103799', '053800123004',
       '23671200000', '764025930000', '889714000038', '076840100477',
       '070800179329', '042222336413', '012000171864', '049000012781',
       '049000010633', '051000228895', '078000010367', '044000039905',
       '071142004089', '050000274444', '071840205009', '077661137833',
       '767707013299', '078300054764', '4131', '034000040476',
       '021000054473', '043000079232', '029000020351', '043000200520',
       '044700009000', '041129412152', '013000798303', '021000043552',
       '087684009000', '029000019201', '792851356565', '044700073933',
       '043000003596', '021000054190', '021131506940', '780993107565',
       '074714086643', '4135', '857183005120', '041449001401',
       '026800001924', '21075100000', '041129634608', '070221006693',
       '021000642182', '041129000052', '021000049318', '511111001768',
       '041244000098', '037000889427', '4078', '511111004127',
       '511111904175', '048001412538', '212245400006', '011110603746',
       '011110974525', '041260362873', '021000658831', '4067',
       '044300107700', '011110073747', '20750000000', '077298000043',
       '021000068852', '021000055005', '044700031711', '029000015630',
       '5000111047524', '043000081099', '043000005217', '049900000345',
       '044700087558', '021000037186', '029000012578', '025400076363',
       '043000204405', '2700710686201', '016000147096', '036000320893',
       '036000495737', '036000432190', '070470400235', '511111003960',
       '043000081501', '048121229030', '041449402529', '021000052363',
       '043000006283', '021000018710', '036000162905', '016000898264',
       '007940018942', '021000049325', '025800020300', '021000024582',
       '600699001564', '016000128620', '070470149394', '043000080443',
       '013000009263', '021000045006', '029000019416', '087684009338',
       '021000054602', '043000058404', '087684004449', '036000494129',
       '021000024674', '013000799102', '043000048528', '021000030453',
       '071159001750', '042800108005', 'B076FJ92M4', 'B07BRRLSVC',
       'B08BGBHHP6', 'B08DQDHR2S', '665290001184'], dtype=object)

#### rewardsReceiptStatus is rejected but pointsAwardedDate is not None

In [90]:
receipts_df[(receipts_df['rewardsReceiptStatus'] == 'REJECTED') & (receipts_df['pointsAwardedDate'].isna() == False)].drop_duplicates()

,rcp_id,bonusPointsEarned,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,barcode,description,finalPrice,itemPrice,quantityPurchased,rewardsReceiptStatus,totalSpent,userId
24,5f9c74f70a7214ad07000037,750.0,2020-10-30,2020-10-30,None,2021-01-03,2020-10-30,750.0,2020-10-29,11.0,075925306254,None,1,1,1.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
25,5f9c74f70a7214ad07000037,750.0,2020-10-30,2020-10-30,None,2021-01-03,2020-10-30,750.0,2020-10-29,11.0,None,None,None,None,NaN,REJECTED,1.00,5f9c74f7c88c1415cbddb839
6116,5fa8d5730a7214adc30001c3,750.0,2020-11-08,2020-11-08,None,2021-01-26,2020-11-08,750.0,2020-11-07,11.0,075925306254,None,1,1,1.0,REJECTED,1.00,5fa8d573770b516dda4f4d21
6117,5fa8d5730a7214adc30001c3,750.0,2020-11-08,2020-11-08,None,2021-01-26,2020-11-08,750.0,2020-11-07,11.0,None,None,None,None,NaN,REJECTED,1.00,5fa8d573770b516dda4f4d21
6854,5fb1bd510a7214ad890000e3,750.0,2020-11-15,2020-11-15,None,2021-02-01,2020-11-15,750.0,2020-11-14,11.0,075925306254,None,1,1,1.0,REJECTED,1.00,5fb1bd519c09d811e5211cef
6855,5fb1bd510a7214ad890000e3,750.0,2020-11-15,2020-11-15,None,2021-02-01,2020-11-15,750.0,2020-11-14,11.0,None,None,None,None,NaN,REJECTED,1.00,5fb1bd519c09d811e5211cef
6883,5fb2da580a7214ad89000114,750.0,2020-11-16,2020-11-16,None,2021-02-01,2020-11-16,750.0,2020-11-15,11.0,075925306254,None,1,1,1.0,REJECTED,1.00,5fb2da582357ec11d4ecc403
6884,5fb2da580a7214ad89000114,750.0,2020-11-16,2020-11-16,None,2021-02-01,2020-11-16,750.0,2020-11-15,11.0,None,None,None,None,NaN,REJECTED,1.00,5fb2da582357ec11d4ecc403

#### For each recript id, check if the total quantityPurchased is eauql to purchasedItemCount

In [106]:
sum_purchase = pd.DataFrame(receipts_df.groupby('rcp_id')['quantityPurchased'].apply('sum')).reset_index()
total_purchase = receipts_df[['rcp_id', 'purchasedItemCount']]
merge = total_purchase.merge(sum_purchase, on = 'rcp_id', how = 'left')
merge[merge['purchasedItemCount'] != merge['quantityPurchased']]['rcp_id'].nunique()

528

#### Conclusion for data quality issues
1. One data quality issue I find in the data is there is exist some rows with conflict information. For example, the table above shows there are 4 rows rcp_id where the  rewardsReceiptStatus is 'REJECTED' but pointsAwardedDate is not None.

2. The second issue I find the there are 528 receipts where the sum of the quantityPurchased of all th items under that receipt is not equal to the purchasedItemCount.